name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "feat/actions" ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  SERVICE: ${{ secrets.SERVICE_NAME }}
  REGION: ${{ secrets.SERVICE_REGION }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GCP_CREDENTIALS }}'

      # BEGIN - Docker auth and build (NOTE: If you already have a container image, these Docker steps can be omitted)

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Log into registry
        uses: 'docker/login-action@v1'
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: ${{ env.DOCKER_USERNAME }}/socilink:latest
          push: true
          file: ./Dockerfile

      - name: Image digest
        run: echo